import React, { useState } from 'react';
import { useERP } from '../context/ERPContext';
import { Invoice, LineItem, Customer, Product } from '../types/erp';
import { InvoicePrintModal } from './InvoicePrintModal';
import {
  FileText,
  Plus,
  Search,
  Filter,
  Printer,
  Copy,
  Truck,
  CreditCard,
  Edit2,
  Trash2,
  CheckCircle2,
  Clock,
  AlertTriangle,
  X,
  ChevronRight,
  Download
} from 'lucide-react';

interface InvoicesViewProps {
  onNavigateToDeliveryNotes?: () => void;
  onNavigateToPayments?: () => void;
}

export const InvoicesView: React.FC<InvoicesViewProps> = ({
  onNavigateToDeliveryNotes,
  onNavigateToPayments,
}) => {
  const {
    invoices,
    customers,
    products,
    company,
    currentUser,
    createInvoice,
    updateInvoice,
    cloneInvoice,
    generateDeliveryNoteFromInvoice,
    deleteInvoice,
    recordPayment,
  } = useERP();

  const [search, setSearch] = useState('');
  const [statusFilter, setStatusFilter] = useState('ALL');
  const [selectedInvoiceForPrint, setSelectedInvoiceForPrint] = useState<Invoice | null>(null);

  // Invoice Create / Edit Modal State
  const [isFormModalOpen, setIsFormModalOpen] = useState(false);
  const [editingInvoice, setEditingInvoice] = useState<Invoice | null>(null);

  // Quick Payment Modal State
  const [isPaymentModalOpen, setIsPaymentModalOpen] = useState(false);
  const [paymentInvoice, setPaymentInvoice] = useState<Invoice | null>(null);
  const [paymentAmount, setPaymentAmount] = useState('');
  const [paymentMethod, setPaymentMethod] = useState<'Bank Transfer / EFT' | 'Cash' | 'Credit/Debit Card' | 'Cheque'>('Bank Transfer / EFT');
  const [paymentRef, setPaymentRef] = useState('');

  // Invoice Form Fields
  const [formData, setFormData] = useState({
    customerId: '',
    branchId: '',
    issueDate: new Date().toISOString().split('T')[0],
    dueDate: new Date(Date.now() + 30 * 86400000).toISOString().split('T')[0],
    notes: '',
    autoGenerateDeliveryNote: true,
    items: [] as LineItem[],
  });

  const [formError, setFormError] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);

  // Total summary calculations
  const totalInvoiced = invoices.reduce((acc, inv) => acc + inv.grandTotal, 0);
  const totalPaid = invoices.reduce((acc, inv) => acc + inv.amountPaid, 0);
  const totalBalanceDue = invoices.reduce((acc, inv) => acc + inv.balanceDue, 0);
  const overdueCount = invoices.filter((inv) => inv.status === 'Overdue').length;

  const openCreateModal = () => {
    setEditingInvoice(null);
    const defaultCust = customers[0];
    const defaultBranch = defaultCust?.branches[0];

    // default 2 items
    const sampleItems: LineItem[] = products.slice(0, 2).map((p) => {
      const qty = 20;
      const sub = qty * p.unitPrice;
      const vat = sub * 0.15;
      return {
        id: 'li_' + Math.random().toString(36).substring(2, 7),
        productId: p.id,
        sku: p.sku,
        description: p.name,
        packSize: p.packSize,
        quantity: qty,
        unitPrice: p.unitPrice,
        vatRate: 15,
        discountPercent: 0,
        subtotal: sub,
        vatAmount: vat,
        total: sub + vat,
      };
    });

    setFormData({
      customerId: defaultCust?.id || '',
      branchId: defaultBranch?.id || '',
      issueDate: new Date().toISOString().split('T')[0],
      dueDate: new Date(Date.now() + 30 * 86400000).toISOString().split('T')[0],
      notes: 'Standard distribution dispatch. EFT settled per invoice reference.',
      autoGenerateDeliveryNote: true,
      items: sampleItems,
    });
    setFormError(null);
    setIsFormModalOpen(true);
  };

  const openEditModal = (inv: Invoice) => {
    setEditingInvoice(inv);
    setFormData({
      customerId: inv.customerId,
      branchId: inv.branchId || '',
      issueDate: inv.issueDate,
      dueDate: inv.dueDate,
      notes: inv.notes,
      autoGenerateDeliveryNote: false,
      items: [...inv.items],
    });
    setFormError(null);
    setIsFormModalOpen(true);
  };

  const handleCustomerChange = (custId: string) => {
    const cust = customers.find((c) => c.id === custId);
    setFormData((prev) => ({
      ...prev,
      customerId: custId,
      branchId: cust?.branches[0]?.id || '',
    }));
  };

  const handleProductSelect = (index: number, productId: string) => {
    const prod = products.find((p) => p.id === productId);
    if (!prod) return;

    setFormData((prev) => {
      const nextItems = [...prev.items];
      const cur = nextItems[index];
      const qty = cur.quantity || 10;
      const subtotal = qty * prod.unitPrice * (1 - cur.discountPercent / 100);
      const vat = subtotal * (prod.vatApplicable ? 0.15 : 0);

      nextItems[index] = {
        ...cur,
        productId: prod.id,
        sku: prod.sku,
        description: prod.name,
        packSize: prod.packSize,
        unitPrice: prod.unitPrice,
        vatRate: prod.vatApplicable ? 15 : 0,
        subtotal: Math.round(subtotal * 100) / 100,
        vatAmount: Math.round(vat * 100) / 100,
        total: Math.round((subtotal + vat) * 100) / 100,
      };
      return { ...prev, items: nextItems };
    });
  };

  const handleItemFieldChange = (index: number, field: string, value: any) => {
    setFormData((prev) => {
      const nextItems = [...prev.items];
      const cur = { ...nextItems[index], [field]: value };
      const qty = Number(cur.quantity) || 0;
      const price = Number(cur.unitPrice) || 0;
      const disc = Number(cur.discountPercent) || 0;
      const vatRate = Number(cur.vatRate) || 15;

      const raw = qty * price;
      const subtotal = raw * (1 - disc / 100);
      const vat = subtotal * (vatRate / 100);

      cur.subtotal = Math.round(subtotal * 100) / 100;
      cur.vatAmount = Math.round(vat * 100) / 100;
      cur.total = Math.round((subtotal + vat) * 100) / 100;

      nextItems[index] = cur;
      return { ...prev, items: nextItems };
    });
  };

  const addItemRow = () => {
    const firstProd = products[0];
    const qty = 10;
    const sub = firstProd ? qty * firstProd.unitPrice : 0;
    const vat = sub * 0.15;
    const newItem: LineItem = {
      id: 'li_' + Date.now() + Math.random().toString(36).substring(2, 5),
      productId: firstProd?.id,
      sku: firstProd?.sku || 'CUSTOM',
      description: firstProd?.name || 'Artisanal Bakery Item',
      packSize: firstProd?.packSize || 'Pack of 12',
      quantity: qty,
      unitPrice: firstProd?.unitPrice || 0,
      vatRate: 15,
      discountPercent: 0,
      subtotal: sub,
      vatAmount: vat,
      total: sub + vat,
    };
    setFormData((prev) => ({ ...prev, items: [...prev.items, newItem] }));
  };

  const removeItemRow = (index: number) => {
    setFormData((prev) => ({
      ...prev,
      items: prev.items.filter((_, i) => i !== index),
    }));
  };

  const handleSubmitInvoice = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!formData.customerId) {
      setFormError('Please select a customer.');
      return;
    }
    if (formData.items.length === 0) {
      setFormError('Please add at least one line item to the invoice.');
      return;
    }

    const cust = customers.find((c) => c.id === formData.customerId);
    const branch = cust?.branches.find((b) => b.id === formData.branchId);

    setIsSubmitting(true);
    setFormError(null);

    try {
      if (editingInvoice) {
        await updateInvoice(editingInvoice.id, {
          customerId: cust?.id,
          customerName: cust?.registeredName,
          customerTradingName: cust?.tradingName,
          branchId: branch?.id,
          branchName: branch?.branchName,
          deliveryAddress: branch?.deliveryAddress || 'Standard Delivery',
          customerVat: cust?.vatNumber,
          issueDate: formData.issueDate,
          dueDate: formData.dueDate,
          items: formData.items,
          notes: formData.notes,
        });
      } else {
        await createInvoice({
          customerId: cust?.id,
          customerName: cust?.registeredName,
          customerTradingName: cust?.tradingName,
          branchId: branch?.id,
          branchName: branch?.branchName,
          deliveryAddress: branch?.deliveryAddress || 'Standard Delivery',
          customerVat: cust?.vatNumber,
          issueDate: formData.issueDate,
          dueDate: formData.dueDate,
          items: formData.items,
          notes: formData.notes,
          autoGenerateDeliveryNote: formData.autoGenerateDeliveryNote,
        });
      }
      setIsFormModalOpen(false);
    } catch (err: any) {
      setFormError(err.message || 'Failed to save invoice');
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleDuplicate = async (inv: Invoice) => {
    try {
      const cloned = await cloneInvoice(inv.id);
      setSelectedInvoiceForPrint(cloned);
    } catch (err: any) {
      alert(err.message || 'Failed to duplicate invoice');
    }
  };

  const handleGenerateDN = async (inv: Invoice) => {
    try {
      await generateDeliveryNoteFromInvoice(inv.id);
      alert(`Linked Delivery Note successfully created for ${inv.invoiceNumber}!`);
      if (onNavigateToDeliveryNotes) onNavigateToDeliveryNotes();
    } catch (err: any) {
      alert(err.message || 'Failed to generate delivery note');
    }
  };

  const openQuickPayment = (inv: Invoice) => {
    setPaymentInvoice(inv);
    setPaymentAmount(String(inv.balanceDue));
    setPaymentRef(`EFT-${inv.invoiceNumber.replace('INV-', '')}`);
    setIsPaymentModalOpen(true);
  };

  const handleSavePayment = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!paymentInvoice || !paymentAmount) return;
    try {
      await recordPayment({
        invoiceId: paymentInvoice.id,
        invoiceNumber: paymentInvoice.invoiceNumber,
        customerId: paymentInvoice.customerId,
        customerName: paymentInvoice.customerName,
        paymentDate: new Date().toISOString().split('T')[0],
        amount: Number(paymentAmount),
        paymentMethod,
        referenceNumber: paymentRef,
        notes: `Settled against ${paymentInvoice.invoiceNumber}`,
      });
      setIsPaymentModalOpen(false);
    } catch (err: any) {
      alert(err.message || 'Failed to record payment');
    }
  };

  const filteredInvoices = invoices.filter((inv) => {
    const term = search.toLowerCase();
    const matchesSearch =
      inv.invoiceNumber.toLowerCase().includes(term) ||
      inv.customerName.toLowerCase().includes(term) ||
      (inv.customerTradingName && inv.customerTradingName.toLowerCase().includes(term)) ||
      (inv.branchName && inv.branchName.toLowerCase().includes(term));

    const matchesStatus = statusFilter === 'ALL' || inv.status === statusFilter;
    return matchesSearch && matchesStatus;
  });

  // Calculate live form totals
  const formSubtotal = formData.items.reduce((acc, it) => acc + (it.subtotal || 0), 0);
  const formVatTotal = formData.items.reduce((acc, it) => acc + (it.vatAmount || 0), 0);
  const formGrandTotal = formSubtotal + formVatTotal;

  return (
    <div className="space-y-6">
      {/* Executive Financial KPI Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="bg-[#171311] border border-[#2C211B] rounded-xl p-4">
          <div className="text-[11px] font-medium text-[#A69385] uppercase tracking-wider mb-1">
            Total Gross Invoiced
          </div>
          <div className="text-xl font-bold font-mono text-white tabular-nums">
            {company.currency} {totalInvoiced.toLocaleString('en-ZA', { minimumFractionDigits: 2 })}
          </div>
          <div className="text-[11px] text-[#8A776B] mt-1 font-mono">
            {invoices.length} invoices generated
          </div>
        </div>

        <div className="bg-[#171311] border border-[#2C211B] rounded-xl p-4">
          <div className="text-[11px] font-medium text-[#A69385] uppercase tracking-wider mb-1">
            Net Paid & Settled
          </div>
          <div className="text-xl font-bold font-mono text-emerald-400 tabular-nums">
            {company.currency} {totalPaid.toLocaleString('en-ZA', { minimumFractionDigits: 2 })}
          </div>
          <div className="text-[11px] text-[#8A776B] mt-1">
            {totalInvoiced > 0 ? `${((totalPaid / totalInvoiced) * 100).toFixed(1)}% collection rate` : '0%'}
          </div>
        </div>

        <div className="bg-[#171311] border border-[#2C211B] rounded-xl p-4">
          <div className="text-[11px] font-medium text-[#A69385] uppercase tracking-wider mb-1">
            Outstanding AR Balance
          </div>
          <div className="text-xl font-bold font-mono text-[#DE9E74] tabular-nums">
            {company.currency} {totalBalanceDue.toLocaleString('en-ZA', { minimumFractionDigits: 2 })}
          </div>
          <div className="text-[11px] text-[#8A776B] mt-1">
            Across active commercial accounts
          </div>
        </div>

        <div className="bg-[#171311] border border-[#2C211B] rounded-xl p-4">
          <div className="text-[11px] font-medium text-[#A69385] uppercase tracking-wider mb-1">
            Overdue Tax Invoices
          </div>
          <div className={`text-xl font-bold font-mono tabular-nums ${overdueCount > 0 ? 'text-rose-400' : 'text-[#EDE6DE]'}`}>
            {overdueCount} Invoices
          </div>
          <div className="text-[11px] text-[#8A776B] mt-1">
            Credit control alert status
          </div>
        </div>
      </div>

      {/* Control Bar: Search, Status Tabs, & Create Button */}
      <div className="flex flex-col sm:flex-row gap-3 items-stretch sm:items-center justify-between">
        <div className="relative flex-1 max-w-md">
          <Search className="w-4 h-4 text-neutral-500 absolute left-3 top-1/2 -translate-y-1/2" />
          <input
            type="text"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Search by invoice #, registered client, branch name..."
            className="w-full pl-9 pr-3 py-2 text-xs bg-neutral-900 border border-neutral-800 rounded-lg text-white placeholder-neutral-500 focus:outline-hidden focus:border-[#C98A5B]"
          />
        </div>

        <div className="flex items-center gap-2 overflow-x-auto">
          {/* Status Tabs */}
          <div className="flex items-center gap-1 p-1 bg-[#171311] border border-[#2C211B] rounded-lg shrink-0">
            {['ALL', 'Draft', 'Sent', 'Partial', 'Paid', 'Overdue'].map((status) => (
              <button
                key={status}
                onClick={() => setStatusFilter(status)}
                className={`px-3 py-1.5 text-xs font-medium rounded-md whitespace-nowrap transition-colors ${
                  statusFilter === status
                    ? 'bg-[#C98A5B] text-[#120F0D] font-bold shadow-xs'
                    : 'text-[#A69385] hover:text-white'
                }`}
              >
                {status}
              </button>
            ))}
          </div>

          <button
            onClick={openCreateModal}
            className="px-4 py-2 rounded-lg bg-[#C98A5B] hover:bg-[#DE9E74] text-[#120F0D] font-bold text-xs transition-colors flex items-center justify-center gap-1.5 shadow-xs shrink-0 whitespace-nowrap"
          >
            <Plus className="w-4 h-4" />
            <span>New Tax Invoice</span>
          </button>
        </div>
      </div>

      {/* Tax Invoices Data Table */}
      <div className="bg-neutral-900 border border-neutral-800 rounded-xl overflow-hidden shadow-xs">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead className="bg-neutral-950/60 border-b border-neutral-800 text-neutral-400 uppercase text-[10px] tracking-wider">
              <tr>
                <th className="py-3 px-4 font-semibold">Invoice Number</th>
                <th className="py-3 px-4 font-semibold">Customer & Branch</th>
                <th className="py-3 px-4 font-semibold">Dates</th>
                <th className="py-3 px-4 font-semibold text-right">Grand Total</th>
                <th className="py-3 px-4 font-semibold text-right">Balance Due</th>
                <th className="py-3 px-4 font-semibold text-center">Status</th>
                <th className="py-3 px-4 font-semibold text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-neutral-800/80">
              {filteredInvoices.length === 0 ? (
                <tr>
                  <td colSpan={7} className="py-10 text-center text-neutral-500">
                    No tax invoices found matching your filters.
                  </td>
                </tr>
              ) : (
                filteredInvoices.map((inv) => {
                  return (
                    <tr key={inv.id} className="hover:bg-neutral-800/40 transition-colors">
                      {/* Invoice Number */}
                      <td className="py-3 px-4">
                        <div className="font-mono font-bold text-[#DE9E74] text-xs">
                          {inv.invoiceNumber}
                        </div>
                        <div className="text-[10px] text-neutral-500 font-mono">
                          {inv.items.length} line items
                        </div>
                      </td>

                      {/* Customer & Branch */}
                      <td className="py-3 px-4">
                        <div className="font-semibold text-white truncate max-w-[200px]">
                          {inv.customerName}
                        </div>
                        <div className="text-[11px] text-neutral-400 truncate max-w-[200px]">
                          {inv.branchName || inv.customerTradingName}
                        </div>
                      </td>

                      {/* Dates */}
                      <td className="py-3 px-4 font-mono text-[11px] text-neutral-400 tabular-nums">
                        <div>Issue: {inv.issueDate}</div>
                        <div className="text-[10px] text-neutral-500">Due: {inv.dueDate}</div>
                      </td>

                      {/* Grand Total */}
                      <td className="py-3 px-4 text-right font-mono font-bold text-white tabular-nums">
                        {company.currency} {inv.grandTotal.toFixed(2)}
                      </td>

                      {/* Balance Due */}
                      <td className="py-3 px-4 text-right font-mono font-bold tabular-nums">
                        <span className={inv.balanceDue > 0 ? 'text-[#DE9E74]' : 'text-emerald-400'}>
                          {company.currency} {inv.balanceDue.toFixed(2)}
                        </span>
                      </td>

                      {/* Status */}
                      <td className="py-3 px-4 text-center">
                        <span
                          className={`inline-block px-2.5 py-0.5 rounded text-[10px] font-semibold uppercase tracking-wider ${
                            inv.status === 'Paid'
                              ? 'bg-emerald-500/15 text-emerald-300 border border-emerald-500/30'
                              : inv.status === 'Partial'
                              ? 'bg-[#C98A5B]/15 text-[#F3D2BF] border border-[#C98A5B]/30'
                              : inv.status === 'Overdue'
                              ? 'bg-red-500/15 text-red-300 border border-red-500/30'
                              : inv.status === 'Sent'
                              ? 'bg-blue-500/15 text-blue-300 border border-blue-500/30'
                              : 'bg-neutral-800 text-neutral-400 border border-neutral-700'
                          }`}
                        >
                          {inv.status}
                        </span>
                      </td>

                      {/* Actions */}
                      <td className="py-3 px-4 text-right">
                        <div className="flex items-center justify-end gap-1.5">
                          {/* Print / View */}
                          <button
                            onClick={() => setSelectedInvoiceForPrint(inv)}
                            className="p-1.5 rounded bg-neutral-800 hover:bg-neutral-700 text-neutral-300 hover:text-white transition-colors"
                            title="View / Print Tax Invoice"
                          >
                            <Printer className="w-3.5 h-3.5" />
                          </button>

                          {/* 1-Click Generate Delivery Note */}
                          <button
                            onClick={() => handleGenerateDN(inv)}
                            className="p-1.5 rounded bg-neutral-800 hover:bg-neutral-700 text-neutral-300 hover:text-[#DE9E74] transition-colors"
                            title="1-Click Generate Delivery Note"
                          >
                            <Truck className="w-3.5 h-3.5" />
                          </button>

                          {/* Record Payment shortcut */}
                          {inv.balanceDue > 0 && (
                            <button
                              onClick={() => openQuickPayment(inv)}
                              className="p-1.5 rounded bg-[#C98A5B]/20 hover:bg-[#C98A5B]/30 text-[#F3D2BF] transition-colors"
                              title="Record Payment against Invoice"
                            >
                              <CreditCard className="w-3.5 h-3.5" />
                            </button>
                          )}

                          {/* Clone */}
                          <button
                            onClick={() => handleDuplicate(inv)}
                            className="p-1.5 rounded bg-neutral-800 hover:bg-neutral-700 text-neutral-300 hover:text-white transition-colors"
                            title="Duplicate / Clone Invoice"
                          >
                            <Copy className="w-3.5 h-3.5" />
                          </button>

                          {/* Edit */}
                          <button
                            onClick={() => openEditModal(inv)}
                            className="p-1.5 rounded bg-neutral-800 hover:bg-neutral-700 text-neutral-300 hover:text-white transition-colors"
                            title="Edit Invoice"
                          >
                            <Edit2 className="w-3.5 h-3.5" />
                          </button>

                          {/* Delete */}
                          <button
                            onClick={() => {
                              if (confirm(`Delete invoice ${inv.invoiceNumber}?`)) {
                                deleteInvoice(inv.id);
                              }
                            }}
                            className="p-1.5 rounded bg-neutral-800 hover:bg-red-950/80 text-neutral-400 hover:text-red-300 transition-colors"
                            title="Delete"
                          >
                            <Trash2 className="w-3.5 h-3.5" />
                          </button>
                        </div>
                      </td>
                    </tr>
                  );
                })
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Invoice Create / Edit Modal */}
      {isFormModalOpen && (
        <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-xs flex items-center justify-center p-3 sm:p-6 overflow-y-auto">
          <div className="w-full max-w-4xl bg-neutral-900 border border-neutral-800 rounded-xl p-6 shadow-2xl my-auto">
            <div className="flex items-center justify-between pb-4 border-b border-neutral-800 mb-4">
              <div>
                <h3 className="text-base font-bold text-white tracking-tight">
                  {editingInvoice ? `Edit Tax Invoice: ${editingInvoice.invoiceNumber}` : 'Create Compliant Tax Invoice'}
                </h3>
                <p className="text-xs text-neutral-400">
                  Itemized billing with automated 15% VAT, customer branch linkage, and auto-generated delivery slips.
                </p>
              </div>
              <button
                onClick={() => setIsFormModalOpen(false)}
                className="p-1 rounded text-neutral-400 hover:text-white hover:bg-neutral-800"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            {formError && (
              <div className="p-3 mb-4 rounded bg-red-950/40 border border-red-800/60 text-xs text-red-300">
                {formError}
              </div>
            )}

            <form onSubmit={handleSubmitInvoice} className="space-y-4">
              {/* Row 1: Customer & Branch Selection */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label className="block text-xs font-medium text-neutral-300 mb-1">
                    Customer Account <span className="text-[#C98A5B]">*</span>
                  </label>
                  <select
                    value={formData.customerId}
                    onChange={(e) => handleCustomerChange(e.target.value)}
                    required
                    className="w-full px-3 py-2 text-xs bg-neutral-800 border border-neutral-700 rounded-md text-white focus:outline-hidden focus:border-[#C98A5B]"
                  >
                    <option value="">Select a Customer...</option>
                    {customers.map((c) => (
                      <option key={c.id} value={c.id}>
                        {c.registeredName} ({c.accountCode})
                      </option>
                    ))}
                  </select>
                </div>

                <div>
                  <label className="block text-xs font-medium text-neutral-300 mb-1">
                    Store Branch / Receiving Destination
                  </label>
                  <select
                    value={formData.branchId}
                    onChange={(e) => setFormData({ ...formData, branchId: e.target.value })}
                    className="w-full px-3 py-2 text-xs bg-neutral-800 border border-neutral-700 rounded-md text-white focus:outline-hidden focus:border-[#C98A5B]"
                  >
                    <option value="">Select Delivery Branch...</option>
                    {customers
                      .find((c) => c.id === formData.customerId)
                      ?.branches.map((b) => (
                        <option key={b.id} value={b.id}>
                          {b.branchName}
                        </option>
                      ))}
                  </select>
                </div>
              </div>

              {/* Row 2: Dates */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label className="block text-xs font-medium text-neutral-300 mb-1">
                    Issue Date
                  </label>
                  <input
                    type="date"
                    value={formData.issueDate}
                    onChange={(e) => setFormData({ ...formData, issueDate: e.target.value })}
                    required
                    className="w-full px-3 py-2 text-xs bg-neutral-800 border border-neutral-700 rounded-md text-white focus:outline-hidden focus:border-[#C98A5B]"
                  />
                </div>

                <div>
                  <label className="block text-xs font-medium text-neutral-300 mb-1">
                    Payment Due Date
                  </label>
                  <input
                    type="date"
                    value={formData.dueDate}
                    onChange={(e) => setFormData({ ...formData, dueDate: e.target.value })}
                    required
                    className="w-full px-3 py-2 text-xs bg-neutral-800 border border-neutral-700 rounded-md text-white focus:outline-hidden focus:border-[#C98A5B]"
                  />
                </div>
              </div>

              {/* Line Items Table with Quick-Pick */}
              <div className="pt-2 border-t border-neutral-800">
                <div className="flex items-center justify-between mb-2">
                  <div className="text-xs font-bold uppercase tracking-wider text-[#DE9E74]">
                    Itemized Product Breakdown
                  </div>
                  <button
                    type="button"
                    onClick={addItemRow}
                    className="px-2.5 py-1 rounded bg-neutral-800 hover:bg-neutral-700 text-[#DE9E74] text-xs font-medium flex items-center gap-1 transition-colors"
                  >
                    <Plus className="w-3.5 h-3.5" />
                    <span>Add Item</span>
                  </button>
                </div>

                <div className="border border-neutral-800 rounded-lg overflow-x-auto">
                  <table className="w-full text-left text-xs min-w-[700px]">
                    <thead className="bg-neutral-950/70 border-b border-neutral-800 text-[10px] text-neutral-400 uppercase">
                      <tr>
                        <th className="py-2 px-3 w-48">Product Quick-Pick</th>
                        <th className="py-2 px-2">Description / Sizing</th>
                        <th className="py-2 px-2 w-20 text-right">Qty</th>
                        <th className="py-2 px-2 w-24 text-right">Price ({company.currency})</th>
                        <th className="py-2 px-2 w-16 text-right">Disc %</th>
                        <th className="py-2 px-2 w-24 text-right">VAT (15%)</th>
                        <th className="py-2 px-3 w-28 text-right">Total</th>
                        <th className="py-2 px-2 w-10 text-center"></th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-neutral-800">
                      {formData.items.map((item, idx) => (
                        <tr key={item.id || idx} className="hover:bg-neutral-800/30">
                          {/* Product select */}
                          <td className="py-2 px-3">
                            <select
                              value={item.productId || ''}
                              onChange={(e) => handleProductSelect(idx, e.target.value)}
                              className="w-full p-1.5 text-xs bg-neutral-800 border border-neutral-700 rounded text-white focus:outline-hidden"
                            >
                              <option value="">Choose Catalog SKU...</option>
                              {products.map((p) => (
                                <option key={p.id} value={p.id}>
                                  {p.sku} - {p.name.substring(0, 24)}...
                                </option>
                              ))}
                            </select>
                          </td>

                          {/* Description */}
                          <td className="py-2 px-2">
                            <input
                              type="text"
                              value={item.description}
                              onChange={(e) => handleItemFieldChange(idx, 'description', e.target.value)}
                              className="w-full p-1.5 text-xs bg-neutral-800/80 border border-neutral-700 rounded text-neutral-200"
                            />
                          </td>

                          {/* Quantity */}
                          <td className="py-2 px-2">
                            <input
                              type="number"
                              min="1"
                              value={item.quantity}
                              onChange={(e) => handleItemFieldChange(idx, 'quantity', Number(e.target.value))}
                              className="w-full p-1.5 text-xs bg-neutral-800 border border-neutral-700 rounded text-right font-mono text-white"
                            />
                          </td>

                          {/* Unit Price */}
                          <td className="py-2 px-2">
                            <input
                              type="number"
                              step="0.01"
                              value={item.unitPrice}
                              onChange={(e) => handleItemFieldChange(idx, 'unitPrice', Number(e.target.value))}
                              className="w-full p-1.5 text-xs bg-neutral-800 border border-neutral-700 rounded text-right font-mono text-white"
                            />
                          </td>

                          {/* Discount */}
                          <td className="py-2 px-2">
                            <input
                              type="number"
                              min="0"
                              max="100"
                              value={item.discountPercent}
                              onChange={(e) => handleItemFieldChange(idx, 'discountPercent', Number(e.target.value))}
                              className="w-full p-1.5 text-xs bg-neutral-800 border border-neutral-700 rounded text-right font-mono text-neutral-300"
                            />
                          </td>

                          {/* VAT */}
                          <td className="py-2 px-2 text-right font-mono tabular-nums text-neutral-400">
                            {company.currency} {item.vatAmount.toFixed(2)}
                          </td>

                          {/* Total */}
                          <td className="py-2 px-3 text-right font-mono font-bold tabular-nums text-[#DE9E74]">
                            {company.currency} {item.total.toFixed(2)}
                          </td>

                          {/* Remove */}
                          <td className="py-2 px-2 text-center">
                            {formData.items.length > 1 && (
                              <button
                                type="button"
                                onClick={() => removeItemRow(idx)}
                                className="text-neutral-500 hover:text-red-400 p-1"
                              >
                                <X className="w-3.5 h-3.5" />
                              </button>
                            )}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>

                {/* Subtotals Box */}
                <div className="flex justify-end mt-3">
                  <div className="w-64 bg-neutral-950/60 border border-neutral-800 rounded-lg p-3 space-y-1 text-xs">
                    <div className="flex justify-between text-neutral-400">
                      <span>Subtotal:</span>
                      <span className="font-mono tabular-nums text-white">
                        {company.currency} {formSubtotal.toFixed(2)}
                      </span>
                    </div>
                    <div className="flex justify-between text-neutral-400">
                      <span>VAT (15% ZAR):</span>
                      <span className="font-mono tabular-nums text-white">
                        {company.currency} {formVatTotal.toFixed(2)}
                      </span>
                    </div>
                    <div className="flex justify-between font-bold text-white border-t border-neutral-800 pt-1 text-sm">
                      <span>Grand Total:</span>
                      <span className="font-mono tabular-nums text-[#DE9E74]">
                        {company.currency} {formGrandTotal.toFixed(2)}
                      </span>
                    </div>
                  </div>
                </div>
              </div>

              {/* Delivery Note Checkbox & Notes */}
              <div className="pt-2 border-t border-neutral-800 grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label className="block text-xs font-medium text-neutral-300 mb-1">
                    Invoice Notes / Delivery Bay Instructions
                  </label>
                  <textarea
                    rows={2}
                    value={formData.notes}
                    onChange={(e) => setFormData({ ...formData, notes: e.target.value })}
                    placeholder="Instructions for offloading bay or transport..."
                    className="w-full px-3 py-2 text-xs bg-neutral-800 border border-neutral-700 rounded-md text-white placeholder-neutral-500 focus:outline-hidden focus:border-[#C98A5B]"
                  />
                </div>

                {!editingInvoice && (
                  <div className="flex items-center p-3 rounded-lg bg-neutral-800/40 border border-neutral-800 self-center">
                    <label className="flex items-center gap-2.5 cursor-pointer text-xs text-neutral-200">
                      <input
                        type="checkbox"
                        checked={formData.autoGenerateDeliveryNote}
                        onChange={(e) => setFormData({ ...formData, autoGenerateDeliveryNote: e.target.checked })}
                        className="rounded border-neutral-700 text-[#C98A5B] focus:ring-[#C98A5B] w-4 h-4 bg-neutral-800"
                      />
                      <div>
                        <div className="font-semibold text-white">Auto-Generate Delivery Note</div>
                        <div className="text-[11px] text-neutral-400">Creates linked delivery slip for receiving clerks</div>
                      </div>
                    </label>
                  </div>
                )}
              </div>

              {/* Form Actions */}
              <div className="pt-4 border-t border-neutral-800 flex items-center justify-end gap-3">
                <button
                  type="button"
                  onClick={() => setIsFormModalOpen(false)}
                  className="px-4 py-2 rounded-lg bg-neutral-800 hover:bg-neutral-700 text-neutral-300 text-xs font-medium transition-colors"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={isSubmitting}
                  className="px-5 py-2 rounded-lg bg-[#C98A5B] hover:bg-[#DE9E74] text-neutral-950 font-semibold text-xs transition-colors flex items-center gap-1.5 shadow-xs"
                >
                  <FileText className="w-4 h-4" />
                  <span>{isSubmitting ? 'Saving...' : editingInvoice ? 'Update Tax Invoice' : 'Generate Tax Invoice'}</span>
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Quick Record Payment Modal */}
      {isPaymentModalOpen && paymentInvoice && (
        <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-xs flex items-center justify-center p-4">
          <div className="w-full max-w-md bg-neutral-900 border border-neutral-800 rounded-xl p-6 shadow-2xl">
            <div className="flex items-center justify-between pb-3 border-b border-neutral-800 mb-4">
              <div>
                <h3 className="text-base font-bold text-white tracking-tight">Record Invoice Payment</h3>
                <p className="text-xs text-neutral-400 font-mono">Invoice #{paymentInvoice.invoiceNumber}</p>
              </div>
              <button
                onClick={() => setIsPaymentModalOpen(false)}
                className="p-1 rounded text-neutral-400 hover:text-white"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            <form onSubmit={handleSavePayment} className="space-y-3">
              <div className="p-3 rounded bg-neutral-800/60 border border-neutral-700 text-xs flex justify-between">
                <span className="text-neutral-400">Outstanding Balance:</span>
                <span className="font-mono font-bold text-[#DE9E74]">
                  {company.currency} {paymentInvoice.balanceDue.toFixed(2)}
                </span>
              </div>

              <div>
                <label className="block text-xs font-medium text-neutral-300 mb-1">
                  Payment Amount ({company.currency})
                </label>
                <input
                  type="number"
                  step="0.01"
                  required
                  value={paymentAmount}
                  onChange={(e) => setPaymentAmount(e.target.value)}
                  className="w-full px-3 py-2 text-xs bg-neutral-800 border border-neutral-700 rounded text-white font-mono"
                />
              </div>

              <div>
                <label className="block text-xs font-medium text-neutral-300 mb-1">
                  Payment Method
                </label>
                <select
                  value={paymentMethod}
                  onChange={(e) => setPaymentMethod(e.target.value as any)}
                  className="w-full px-3 py-2 text-xs bg-neutral-800 border border-neutral-700 rounded text-white"
                >
                  <option value="Bank Transfer / EFT">Bank Transfer / EFT</option>
                  <option value="Cash">Cash</option>
                  <option value="Credit/Debit Card">Credit/Debit Card</option>
                  <option value="Cheque">Cheque</option>
                </select>
              </div>

              <div>
                <label className="block text-xs font-medium text-neutral-300 mb-1">
                  Reference / Deposit Number
                </label>
                <input
                  type="text"
                  required
                  value={paymentRef}
                  onChange={(e) => setPaymentRef(e.target.value)}
                  className="w-full px-3 py-2 text-xs bg-neutral-800 border border-neutral-700 rounded text-white font-mono"
                />
              </div>

              <div className="pt-3 border-t border-neutral-800 flex justify-end gap-2">
                <button
                  type="button"
                  onClick={() => setIsPaymentModalOpen(false)}
                  className="px-3 py-1.5 text-xs text-neutral-300 hover:text-white"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-4 py-1.5 rounded bg-emerald-500 hover:bg-emerald-400 text-neutral-950 font-semibold text-xs transition-colors"
                >
                  Confirm & Deduct Balance
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Printable Tax Invoice Modal */}
      {selectedInvoiceForPrint && (
        <InvoicePrintModal
          invoice={selectedInvoiceForPrint}
          onClose={() => setSelectedInvoiceForPrint(null)}
        />
      )}
    </div>
  );
};
